### ISSUE TITLE
Hugepages are no longer able to be used

### ISSUE THREAD

**Issue by edstewbob** [webchain-network/webchain-miner#15]
The current 2.8 CPU miner does not used hugepages even when they are activate in both Windows and Linux. The old 2.7 miner used hugepages for increased hash rate but the new miner does not. Please see what can be don't to re-activate hugepages usage.

**Comment by DareVanReed** [comment]
+1, same behavior on Debian 9

**Comment by Orfeous** [comment]
+1 on Debian 10
+1 on Windows 10

**Comment by Incrediblez7** [comment]
+1 on MacOS 10.15 Beta(19A582a) (Still happening in 2.8)
