### ISSUE TITLE
Hashrate variance from v2.5.3 to v2.6.2

### ISSUE THREAD

**Issue by DeonBonthuys** [webchain-network/webchain-miner#3]
I configured and fired up v2.6.2 with the same config used in v2.5.3 and my max hashrate dropped from 95 to 75 and average hashrate dropped from 91 to 65. This is on an i7 7700HQ L2/L3 1/6mb.

**Comment by lukaszmatczak** [comment]
Could you also provide info about your operating system and attach your config file?

**Comment by DeonBonthuys** [comment]
OS is Windows 10.
Config below:
{                                                                                                             
    "algo": "cryptonight-webchain",
    "av": 0,                // algorithm variation, 0 auto select                                             
    "background": false,    // true to run the miner in the background                                        
    "colors": true,         // false to disable colored output                                                
    "cpu-affinity": null,   // set process affinity to CPU core(s), mask "0x3" for cores 0 and 1              
    "cpu-priority": null,   // set process priority (0 idle, 2 normal to 5 highest)                           
    "donate-level": 1,      // donate level, mininum 1%                                                       
    "log-file": null,       // log all output to a file, example: "c:/some/path/webchain-miner.log"           
    "max-cpu-usage": 100,    // maximum CPU usage for automatic mode, usually limiting factor is CPU cache not this option.                                                                                                  
    "print-time": 60,       // print hashrate report every N seconds                                          
    "retries": 5,           // number of times to retry before switch to backup server                        
    "retry-pause": 5,       // time to pause between retries                                                  
    "safe": true,          // true to safe adjust threads and av settings for current CPU                    
    "syslog": false,        // use system log for output messages                                             
    "threads": null,        // number of miner threads                                                           
    "pools": [
        {
            "url": "pool.webchain.network:2222", // URL of mining server
            "user": "0x8ed0f839abcaa7ec8b44090fe44507b4d455dd1a",               // username for mining server
            "pass": "x",                         // password for mining server
            "worker-id": "0",                    // worker ID for mining server
            "keepalive": false,                  // send keepalived for prevent timeout (need pool support)
            "nicehash": false
        }
    ],
    "api": {
        "port": 0,                             // port for the miner API https://github.com/xmrig/xmrig/wiki/API
        "access-token": null,                  // access token for API
        "worker-id": null                      // custom worker-id for API
    }
}

Did some more testing, ran both versions separately for around 10min to have it even out over time but the average hashrate still varied by 20 between the versions, latest version being lower.

**Comment by lukaszmatczak** [comment]
Number of used threads can be different on these versions. Could you please confirm it? I mean this line: `[2018-10-25 15:14:13] READY (CPU) threads 1(1) huge pages 0/1 0% memory 2.0 MB`.
If yes, you can specify number of threads in config manually.

**Comment by lukaszmatczak** [comment]
Please also try to force algorithm variation to 1 in config:
```"av": 1```

**Comment by DeonBonthuys** [comment]
Setting av: 1 seems to have made a difference. Median average is higher. 
NB: I tested both versions on a different CPU i7 4710HQ and i got the exact same hashrate between them (without changing the av).
Side note: The 4th gen runs at 130h/s while the 7th gen only gets around 90h/s. Both with 1/6mb L2/L3 cache at the same frequency. With any CPU friendly algo. Would love to know why (not expecting you to know the answer to this, just putting it out there lol).

**Comment by pahanzt** [comment]
I believe issue was solved. Closing.
