### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by Quillbert** [webchain-network/webchain-miner#7]
Is it possible to compile the miner for a raspberry pi?

**Comment by psharma04** [comment]
It should be, following the same instructions as XMRig. I'm getting stuck when the makefile asks for Cryptonight_monero.h. I will send a link if I manage to compile it.

**Comment by lukaszmatczak** [comment]
@psharma04 Could you paste here full error message? It shouldn't ask for CryptoNight_monero.h because in webchain-miner we have CryptoNight_webchain.h instead: https://github.com/webchain-network/webchain-miner/blob/master/src/crypto/CryptoNight_webchain.h
